const SUPABASE_URL = 'https://wqkihxadcxmxgicixlww.supabase.co';
const SUPABASE_KEY = 'sb_publishable_vgt7oNKoGwJyDsCvVmYMXw_Y3APibq4';

const SITE_CONFIG = {
  "fortunecoins.com":      { name: "Fortune Coins",    launch_url: "https://fortunewins.com/lobby" },
  "megabonanza.com":       { name: "Mega Bonanza" },
  "rolla.com":             { name: "Rolla" },
  "rollingriches.com":     { name: "Rolling Riches" },
  "modo.us":               { name: "Modo" },
  "rebet.app":             { name: "Rebet" },
  "chanced.com":           { name: "Chanced",          launch_url: "https://chanced.com/?tab=bank&page=bonus" },
  "goldenheartsgames.com": { name: "Golden Hearts" },
  "shuffle.us":            { name: "Shuffle",           launch_url: "https://shuffle.us/?md-tab=Daily+Bonus&modal=wallet" },
  "globalpoker.com":       { name: "Global Poker" },
  "punt.com":              { name: "Punt" },
  "playfame.com":          { name: "PlayFame" },
  "luckparty.com":         { name: "Luckparty" },
  "sportzino.com":         { name: "Sportzino" },
  "clubs.poker":           { name: "Clubs Poker",       aliases: ["ClubsPoker"], launch_url: "https://play.clubspoker.com/d/?tables/all&_gl=1*1njthbq*_gcl_au*NTc4NzcwOTgxLjE3NzYwNDc0Nzg." },
  "high5casino.com":       { name: "High5" },
  "yaycasino.com":         { name: "Yay Casino" },
  "americanluck.com":      { name: "American Luck" },
  "zulacasino.com":        { name: "Zula" },
  "moozi.com":             { name: "Moozi" },
  "moonspin.us":           { name: "Moonspin" },
  "lonestarcasino.com":    { name: "LoneStar" },
  "realprize.com":         { name: "RealPrize" },
  "crowncoinscasino.com":  { name: "CrownCoins" },
  "pulsz.com":             { name: "Pulsz" },
  "wowvegas.com":          { name: "WOW Vegas" },
  "chumbacasino.com":      { name: "Chumba Casino" },
  "sidepot.us":            { name: "Sidepot" },
  "spree.com":             { name: "Spree" },
  "spinpals.com":          { name: "SpinPals",          aliases: ["Spinpals"], launch_url: "https://www.spinpals.com/user/reward/daily-bonus" },
  "stake.us":              { name: "Stake",             launch_url: "https://stake.us/?tab=dailyBonus&currency=btc&modal=wallet" },
  "spinquest.com":         { name: "SpinQuest" },
  "coinz.us":              { name: "Coinz" },
  "legendz.com":           { name: "Legendz" },
  "dogghousecasino.com":   { name: "Dogghouse",         aliases: ["Dogghouse Casino"], launch_url: "https://play.dogghousecasino.com/profile" },
  "chipnwin.com":          { name: "ChipnWin" },
  "sweetsweeps.com":       { name: "SweetSweeps" },
  "lunalandcasino.com":    { name: "LunaLand" },
  "myprize.us":            { name: "MyPrize" },
  "ace.com":               { name: "Ace",              launch_url: "https://www.ace.com/gold-coins" },
  "goldmachine.com":       { name: "Gold Machine" },
  "spindoo.us":            { name: "Spindoo",           launch_url: "https://www.spindoo.us/gold-coins" },
  "jackpota.com":          { name: "Jackpota" },
  "mcluck.com":            { name: "McLuck" },
  "hellomillions.com":     { name: "Hello Millions" },
  "spinblitz.com":         { name: "SpinBlitz" },
  "zoot.us":               { name: "Zoot" },
  "sheeshcasino.com":      { name: "Sheesh",            launch_url: "https://sheeshcasino.com/daily-bonus" },
  "sweepjungle.com":       { name: "SweepJungle" },
  "cashoomo.com":          { name: "Cashoomo" },
  "vegawin.com":           { name: "Vegawin" },
  "sweepsusa.com":         { name: "Sweep USA" },
  "luckyhands.com":        { name: "LuckyHands" },
  "epicsweep.us":          { name: "Epic Sweeps" },
  "sixty6.com":            { name: "Sixty6",            launch_url: "https://sixty6.com/home?modal=dailyRefill" },
  "luckyone.us":           { name: "Luckyone" },
  "luckystake.com":        { name: "Lucky Stake" },
  "babacasino.com":        { name: "Baba Casino" },
  "daracasino.com":        { name: "Dara Casino" },
  "luckylandslots.com":    { name: "LuckyLand Slots" },
  "luckylandcasino.com":   { name: "LuckyLand Casino" },
  "winbonanza.com":        { name: "Win Bonanza",       launch_url: "https://winbonanza.com/lobby" },
  "dimesweeps.com":        { name: "Dime Sweeps",       launch_url: "https://dimesweeps.com/" },
  "sweepsroyal.com":       { name: "Sweeps Royal",      launch_url: "https://www.sweepsroyal.com/" },
  "speedsweeps.com":       { name: "Speed Sweeps",      launch_url: "https://speedsweeps.com/" },
  "richsweeps.com":        { name: "Rich Sweeps",       launch_url: "https://richsweeps.com/" },
  "bangcoins.com":         { name: "Bang Coins",        launch_url: "https://bangcoins.com/" },
  "jackpotgo.com":         { name: "Jackpot Go",        launch_url: "https://game.jackpotgo.com/?channel=official_website&campaign=official_website" }
};

const { createClient } = supabase;
const sb = createClient(SUPABASE_URL, SUPABASE_KEY);
