const SUPABASE_URL = 'https://wqkihxadcxmxgicixlww.supabase.co';
const SUPABASE_KEY = 'sb_publishable_vgt7oNKoGwJyDsCvVmYMXw_Y3APibq4';

const SITE_CONFIG = {
  "fortunecoins.com":      { name: "Fortune Coins",    selector: ".FCButtonItem.FCoins div.textDecimals.mobile span", launch_url: "https://fortunewins.com/lobby" },
  "megabonanza.com":       { name: "Mega Bonanza",     selector: "span[class*='currencyValue'][style*='width']" },
  "rolla.com":             { name: "Rolla",            selector: "div.ring-sweep-400:has(img[alt='RSC coin icon']) span" },
  "rollingriches.com":     { name: "Rolling Riches",   selector: "div.sc-coin.active span:not(.coin-amount)" },
  "modo.us":               { name: "Modo",             selector: "button[data-testid='sc-button'] p span" },
  "rebet.app":             { name: "Rebet",            selector: ".MuiBox-root:has(img[src*='sc-icon']) span.MuiTypography-root" },
  "chanced.com":           { name: "Chanced",          selector: "header button:has(img[src*='cash']) span", launch_url: "https://chanced.com/?tab=bank&page=bonus" },
  "goldenheartsgames.com": { name: "Golden Hearts",    selector: "button[data-testid='current-currency-balance-info']" },
  "shuffle.us":            { name: "Shuffle",          selector: "button#SC", launch_url: "https://shuffle.us/?md-tab=Daily+Bonus&modal=wallet" },
  "globalpoker.com":       { name: "Global Poker",     selector: "div#sc-balance-display" },
  "punt.com":              { name: "Punt",             selector: ".shrink.truncate" },
  "playfame.com":          { name: "PlayFame",         selector: "span:has(> span[class*='currencyName'])" },
  "luckparty.com":         { name: "Luckparty",        selector: ".sc-part" },
  "sportzino.com":         { name: "Sportzino",        selector: ".balance-switcher-button-fc" },
  "clubs.poker":           { name: "Clubs Poker",      selector: ".SwitchCurrenciesContainer__currency_balance", launch_url: "https://play.clubspoker.com/d/?tables/all&_gl=1*1njthbq*_gcl_au*NTc4NzcwOTgxLjE3NzYwNDc0Nzg." },
  "high5casino.com":       { name: "High5",            selector: ".sweeps-balance.sc .sweeps-balance-label-amount" },
  "yaycasino.com":         { name: "Yay Casino",       selector: ".FCButtonItem.FCoins" },
  "americanluck.com":      { name: "American Luck",    selector: ".balance-switch__value-button--sc" },
  "zulacasino.com":        { name: "Zula",             selector: ".FCButtonItem.FCoins" },
  "moozi.com":             { name: "Moozi",            selector: "#silver-coin-trigger span" },
  "moonspin.us":           { name: "Moonspin",         selector: "button:has(img[src*='sweep-coin'])" },
  "lonestarcasino.com":    { name: "LoneStar",         selector: ".gcnum .gct" },
  "realprize.com":         { name: "RealPrize",        selector: "div.gcnum span.gct" },
  "crowncoinscasino.com":  { name: "CrownCoins",       selector: "[data-testid='lobby-balance-bar']" },
  "pulsz.com":             { name: "Pulsz",            selector: "[data-test='header-sweepstakes-value']" },
  "wowvegas.com":          { name: "WOW Vegas",        selector: "button[id^='headlessui-menu-button'] div.flex-none" },
  "chumbacasino.com":      { name: "Chumba Casino",    selector: "#top-hud__currency-bar__sweeps-currency-amount span.counter__value" },
  "sidepot.us":            { name: "Sidepot",          selector: "button:has(img[src*='sweep-coin'])" },
  "spree.com":             { name: "Spree",            selector: "number-flow-react[aria-label]" },
  "spinpals.com":          { name: "SpinPals",         selector: "div.border-deepPurple-300 p.text-white", launch_url: "https://www.spinpals.com/user/reward/daily-bonus" },
  "stake.us":              { name: "Stake",            selector: "span.ds-body-md-strong[style*='max-width: 16ch']", launch_url: "https://stake.us/?tab=dailyBonus&currency=btc&modal=wallet" },
  "spinquest.com":         { name: "SpinQuest",        selector: "p[data-sentry-source-file='amounts.tsx']" },
  "coinz.us":              { name: "Coinz",            selector: "#player-balance-value" },
  "legendz.com":           { name: "Legendz",          selector: "div[class*='eyrgspp0']" },
  "dogghousecasino.com":   { name: "Dogghouse",        selector: ".MuiBox-root:has(img[src*='sc-icon']) span.MuiTypography-root", launch_url: "https://play.dogghousecasino.com/profile" },
  "chipnwin.com":          { name: "ChipnWin",         selector: ".nav-bar-header__top div.flex_center_between.background_282D44.pointer" },
  "sweetsweeps.com":       { name: "SweetSweeps",      selector: ".MuiBox-root:has(img[src*='sc-icon.png']) > span.MuiTypography-root" },
  "lunalandcasino.com":    { name: "LunaLand",         selector: "span#balance-sc-coin" },
  "myprize.us":            { name: "MyPrize",          selector: ".active-currency-section .amount" },
  "ace.com":               { name: "Ace",              selector: "[data-test='sc-balance'] span[class*='currencyValue']", launch_url: "https://www.ace.com/gold-coins" },
  "goldmachine.com":       { name: "Gold Machine",     selector: "button:has(span[class*='tabular-nums'])" },
  "spindoo.us":            { name: "Spindoo",          selector: "div[data-test='sc-balance'] span", launch_url: "https://www.spindoo.us/gold-coins" },
  "jackpota.com":          { name: "Jackpota",         selector: "div:has(img[alt='SC icon']):has(button[aria-label='Info']) span" },
  "mcluck.com":            { name: "McLuck",           selector: "span[data-test='common-header-sc-value']" },
  "hellomillions.com":     { name: "Hello Millions",   selector: "div[data-test='sc-balance'] span" },
  "spinblitz.com":         { name: "SpinBlitz",        selector: "span[data-test='sc-balance-value']" },
  "zoot.us":               { name: "Zoot",             selector: "span.chakra-text" },
  "sheeshcasino.com":      { name: "Sheesh",           selector: "div:has(img[src*='sc-icon']) span.text-lime-500", launch_url: "https://sheeshcasino.com/daily-bonus" },
  "sweepjungle.com":       { name: "SweepJungle",      selector: "p.font-lilita" },
  "cashoomo.com":          { name: "Cashoomo",         selector: "span.coins__balance" },
  "vegawin.com":           { name: "Vegawin",          selector: "span.sidebar-balance:has(img[alt='Silver'])" },
  "sweepsusa.com":         { name: "Sweep USA",        selector: "div:has(img[src*='notes.svg']) span" },
  "luckyhands.com":        { name: "LuckyHands",       selector: "span[style*='--accent-acid']" },
  "epicsweep.us":          { name: "Epic Sweeps",      selector: "span.text-primary.font-bold" },
  "sixty6.com":            { name: "Sixty6",           selector: "p.font-lato.text-neutral-100", launch_url: "https://sixty6.com/home?modal=dailyRefill" },
  "luckyone.us":           { name: "Luckyone",         selector: "span.text-shade-10.font-extrabold" },
  "luckystake.com":        { name: "Lucky Stake",      selector: "WAITING_FOR_SELECTOR" },
  "babacasino.com":        { name: "Baba Casino",      selector: "" },
  "daracasino.com":        { name: "Dara Casino",      selector: "" },
  "luckylandslots.com":    { name: "LuckyLand Slots",  selector: "" },
  "luckylandcasino.com":   { name: "LuckyLand Casino", selector: "" },
  "winbonanza.com":        { name: "Win Bonanza",      selector: "", launch_url: "https://winbonanza.com/lobby" }
};

const { createClient } = supabase;
const sb = createClient(SUPABASE_URL, SUPABASE_KEY);
